# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: kourier/kourier
  local:
    push: true
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
test:
  - image: kourier/kourier
    structureTests:
      - ./test/container.yml
deploy:
  kubectl:
    manifests:
      - deploy/*.yml
