### specific kourier events listener
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consumers.kourier.io
spec:
  group: kourier.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: consumers
    singular: consumer
    kind: consumers
    shortNames: ["c"]
  additionalPrinterColumns:
    - name: Owner
      type: string
      JSONPath: .spec.controller
    - name: Listen
      type: string
      JSONPath: .spec.listen
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            controller:
              type: string
            schema:
              type: object
            update:
              type: string
            replace:
              type: string
            listen:
              type: string
            defaults:
              type: object
