### generate kourier events from external systems, ex.: webhook
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: producers.kourier.io
spec:
  group: kourier.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: producers
    singular: producer
    kind: producers
    shortNames: ["p"]
  additionalPrinterColumns:
    - name: Owner
      type: string
      JSONPath: .spec.controller
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            controller:
              type: string
            schema:
              type: object
            update:
              type: string
            replace:
              type: string
            config:
              type: object
